parameters:
  webit_ext_js.tree_store_abstract.class: Webit\Bundle\ExtJsBundle\TreeStore\TreeStoreAbstract
  webit_ext_js.entity_store.class: Webit\Bundle\ExtJsBundle\Store\EntityStore
  webit_ext_js.store_abstract.class: Webit\Bundle\ExtJsBundle\Store\StoreAbstract
  webit_ext_js.controller.extjs.class: Webit\Bundle\ExtJsBundle\Controller\ExtJsController
  webit_ext_js.controller_store.class: Webit\Bundle\ExtJsBundle\Controller\StoreController
  webit_ext_js.controller_tree_store.class: Webit\Bundle\ExtJsBundle\Controller\TreeStoreController
  webit_ext_js.static_data_exposer.class: Webit\Bundle\ExtJsBundle\StaticData\StaticDataExposer
  
services:
  webit_ext_js.tree_store_abstract:
    class: %webit_ext_js.tree_store_abstract.class%
    calls:
      - [setContainer, ["@service_container"]]
      - [init]

  webit_ext_js.store_abstract:
    class: %webit_ext_js.tree_store_abstract.class%
    calls:
      - [setContainer, ["@service_container"]]
      - [init]

  webit_ext_js.controller_store:
    class: %webit_ext_js.controller_store.class%
    calls:
        - [setContainer, ["@service_container"]]

  webit_ext_js.controller_tree_store:
    class: %webit_ext_js.controller_tree_store.class%
    calls:
        - [setContainer, [ "@service_container" ]]

  webit_ext_js.static_data_exposer:
    class: %webit_ext_js.static_data_exposer.class%

  webit_ext_js.controller.extjs:
    class: %webit_ext_js.controller.extjs.class%
    arguments: ["@fos_rest.view_handler"]
    calls:
        - [setContainer, ["@service_container"]]

  webit_ext_js.entity_store:
    class: %webit_ext_js.entity_store.class%
    arguments: [{}, "@doctrine.orm.entity_manager"]
    abstract: true
